default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: crypto_exchange_development

test:
  <<: *default
  database: crypto_exchange_test

production:
  <<: *default
  database: crypto_exchange_production
  username: root
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>